// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKvXc1WoVGwGY0Yn0p-Yb6FGRVmTY-F48',
    appId: '1:606701428212:web:73710590ba6e32dfe3ada1',
    messagingSenderId: '606701428212',
    projectId: 'chatmate-312a9',
    authDomain: 'chatmate-312a9.firebaseapp.com',
    databaseURL: 'https://chatmate-312a9-default-rtdb.firebaseio.com',
    storageBucket: 'chatmate-312a9.appspot.com',
    measurementId: 'G-ZZS4JLBXBL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnJRLneMBj54yQdPXSoPMTTViaoMpXXBE',
    appId: '1:606701428212:android:88f940f27e828ae2e3ada1',
    messagingSenderId: '606701428212',
    projectId: 'chatmate-312a9',
    databaseURL: 'https://chatmate-312a9-default-rtdb.firebaseio.com',
    storageBucket: 'chatmate-312a9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_jJ-8c5jgXOyk-YxDd6z-PHVsPgbQXm8',
    appId: '1:606701428212:ios:fa4b498cf3946545e3ada1',
    messagingSenderId: '606701428212',
    projectId: 'chatmate-312a9',
    databaseURL: 'https://chatmate-312a9-default-rtdb.firebaseio.com',
    storageBucket: 'chatmate-312a9.appspot.com',
    androidClientId: '606701428212-29lfd25pagl7bmcgmof5rmbkmjhjdr4j.apps.googleusercontent.com',
    iosClientId: '606701428212-srtcqfj0uqe5o6c9cn6p6hlf8v343bco.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatmate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_jJ-8c5jgXOyk-YxDd6z-PHVsPgbQXm8',
    appId: '1:606701428212:ios:fa4b498cf3946545e3ada1',
    messagingSenderId: '606701428212',
    projectId: 'chatmate-312a9',
    databaseURL: 'https://chatmate-312a9-default-rtdb.firebaseio.com',
    storageBucket: 'chatmate-312a9.appspot.com',
    androidClientId: '606701428212-29lfd25pagl7bmcgmof5rmbkmjhjdr4j.apps.googleusercontent.com',
    iosClientId: '606701428212-srtcqfj0uqe5o6c9cn6p6hlf8v343bco.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatmate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCKvXc1WoVGwGY0Yn0p-Yb6FGRVmTY-F48',
    appId: '1:606701428212:web:084346690c858226e3ada1',
    messagingSenderId: '606701428212',
    projectId: 'chatmate-312a9',
    authDomain: 'chatmate-312a9.firebaseapp.com',
    databaseURL: 'https://chatmate-312a9-default-rtdb.firebaseio.com',
    storageBucket: 'chatmate-312a9.appspot.com',
    measurementId: 'G-GFJ554M2PE',
  );

}